spring:
  profiles:
    active: nonprod
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: nonprod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
clients:
  family:
    url: http://localhost:3000
---
spring:
  profiles: prod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: test
